# Generated by Django 3.0.7 on 2020-06-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=64)),
                ('sha256', models.CharField(default='', max_length=128)),
                ('filesize', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mimetype', models.CharField(default='', max_length=36)),
            ],
        ),
    ]
