# Generated by Django 3.0.7 on 2020-06-27 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date_finnished',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 13, 31, 44, 214669)),
        ),
        migrations.AddField(
            model_name='file',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 13, 31, 44, 214644)),
        ),
    ]
