# Generated by Django 3.0.7 on 2020-06-27 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20200627_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_finnished',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 13, 32, 28, 511207, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 13, 32, 28, 511183, tzinfo=utc)),
        ),
    ]
