# Generated by Django 3.0.7 on 2020-06-28 05:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20200627_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_finnished',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 5, 57, 20, 260313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 5, 57, 20, 260289, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='filesize',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
