# Generated by Django 3.0.7 on 2020-06-30 04:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20200628_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted', models.BooleanField(default=False)),
                ('file_abs_path', models.BooleanField(default='', max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='date_finnished',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 4, 17, 41, 312126, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 4, 17, 41, 312102, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='file',
            name='metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.FileMetadata'),
        ),
    ]
