# Generated by Django 3.0.7 on 2020-06-30 04:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20200630_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_finnished',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 4, 27, 28, 224619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 4, 27, 28, 224593, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='file_abs_path',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
