# Generated by Django 3.0.7 on 2020-06-30 04:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_auto_20200630_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_finnished',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 4, 45, 18, 263803, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 4, 45, 18, 263780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='filesize',
            field=models.IntegerField(default=0),
        ),
    ]
