# Generated by Django 3.0.7 on 2020-06-30 04:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_auto_20200630_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='sha256',
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='sha256',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_finnished',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 4, 47, 15, 692422, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 4, 47, 15, 692398, tzinfo=utc)),
        ),
    ]
