# Generated by Django 3.0.7 on 2020-06-30 05:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0014_auto_20200630_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='demo.File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_finnished',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 5, 29, 6, 446402, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 5, 29, 6, 446379, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('certificate_metadata', models.TextField(default='', max_length=128)),
                ('ip_address', models.TextField(default='', max_length=20)),
                ('evaluations', models.ManyToManyField(to='demo.Evaluation')),
            ],
        ),
    ]
