# Generated by Django 3.0.7 on 2020-06-30 05:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_auto_20200630_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_finnished',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 5, 31, 49, 860347, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 5, 31, 49, 860322, tzinfo=utc)),
        ),
    ]
