# Generated by Django 3.0.7 on 2020-06-30 05:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0016_auto_20200630_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='evaluations',
            field=models.ManyToManyField(to='demo.File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_finnished',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 5, 43, 45, 540827, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 5, 43, 45, 540802, tzinfo=utc)),
        ),
    ]
